[package]
name = "data_struct"
version = "0.1.0"
authors = ["MarceloBRN <marcelognesp@gmail.com>"]

[dependencies]
num = "0.2"
heapsize = "0.4.2"

[profile.test]
opt-level = 3

[profile.dev]
opt-level = 3